[2022-06-24 08:06:21.719] [remoteagent] [info] Extension host agent started.
[2022-06-24 08:06:22.344] [remoteagent] [info] [127.0.0.1][ee1dad0b][ManagementConnection] New connection established.
[2022-06-24 08:06:22.450] [remoteagent] [info] [127.0.0.1][004e96f5][ExtensionHostConnection] New connection established.
[2022-06-24 08:06:22.456] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:22.461] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:22.474] [remoteagent] [info] [127.0.0.1][004e96f5][ExtensionHostConnection] <1400> Launched Extension Host Process.
[2022-06-24 08:06:22.740] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:23.392] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:23.402] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:23.405] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:23.419] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:24.818] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:24.838] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:25.413] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:25.955] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:36.477] [remoteagent] [info] [127.0.0.1][ee1dad0b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-06-24 08:06:42.599] [remoteagent] [info] [127.0.0.1][5444e417][ManagementConnection] New connection established.
[2022-06-24 08:06:42.708] [remoteagent] [info] [127.0.0.1][158be16a][ExtensionHostConnection] New connection established.
[2022-06-24 08:06:42.740] [remoteagent] [info] [127.0.0.1][158be16a][ExtensionHostConnection] <1488> Launched Extension Host Process.
[2022-06-24 08:06:43.341] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:43.364] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:43.373] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:43.389] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:43.835] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:43.846] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:45.225] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:06:45.330] [remoteagent] [error] ["Error: Could not find pty on pty host","    at w._throwIfNoPty (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:20:5333)","    at w.updateTitle (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:20:1673)","    at Object.call (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:13:8386)","    at h.onPromise (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:4891)","    at h.onRawMessage (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:4274)","    at /home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:12:3560","    at E.invoke (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:145)","    at W.deliver (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:2271)","    at c.fire (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:8:1849)","    at process.U (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/platform/terminal/node/ptyHostMain.js:6:35698)","    at process.emit (node:events:390:28)","    at emit (node:internal/child_process:917:12)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-06-24 08:06:45.857] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:39.972] [remoteagent] [info] [127.0.0.1][5444e417][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-06-24 08:08:45.787] [remoteagent] [info] [127.0.0.1][8908c05a][ManagementConnection] New connection established.
[2022-06-24 08:08:45.807] [remoteagent] [info] [127.0.0.1][d85e3f6c][ExtensionHostConnection] New connection established.
[2022-06-24 08:08:45.822] [remoteagent] [info] [127.0.0.1][d85e3f6c][ExtensionHostConnection] <1600> Launched Extension Host Process.
[2022-06-24 08:08:46.484] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:46.497] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:46.522] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:47.014] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:47.030] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:48.729] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:48.962] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:08:49.369] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:11:42.783] [remoteagent] [info] [127.0.0.1][004e96f5][ExtensionHostConnection] <1400> Extension Host Process exited with code: 0, signal: null.
[2022-06-24 08:13:46.151] [remoteagent] [info] [127.0.0.1][158be16a][ExtensionHostConnection] <1488> Extension Host Process exited with code: 0, signal: null.
[2022-06-24 08:13:49.078] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:18:49.292] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:23:49.498] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:28:49.757] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:30:54.322] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:33:49.975] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:38:50.197] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:43:50.429] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:48:50.646] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:53:51.016] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 08:58:51.284] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 09:03:51.453] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 09:08:51.670] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 09:13:51.887] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 09:32:48.892] [remoteagent] [info] [127.0.0.1][8908c05a][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-06-24 09:32:48.901] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/pi/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/server/node/server.main.js:143:7923)
    at process.emit (node:events:390:28)
[2022-06-24 10:08:02.611] [remoteagent] [info] [127.0.0.1][8908c05a][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-06-24 10:08:02.613] [remoteagent] [info] [127.0.0.1][ee7df092][ManagementConnection] New connection established.
[2022-06-24 10:08:02.633] [remoteagent] [info] [127.0.0.1][ec32da6a][ExtensionHostConnection] New connection established.
[2022-06-24 10:08:02.650] [remoteagent] [info] [127.0.0.1][ec32da6a][ExtensionHostConnection] <6706> Launched Extension Host Process.
[2022-06-24 10:08:03.397] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:03.435] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:03.451] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:04.679] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:04.693] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:05.590] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:05.826] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:08:06.346] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:13:02.818] [remoteagent] [info] [127.0.0.1][8908c05a][ManagementConnection] The reconnection short grace time of 5m has expired, so the connection will be disposed.
[2022-06-24 10:13:02.873] [remoteagent] [info] [127.0.0.1][d85e3f6c][ExtensionHostConnection] <1600> Extension Host Process exited with code: 0, signal: null.
[2022-06-24 10:13:04.695] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
[2022-06-24 10:18:05.437] [remoteagent] [error] [/home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30]: Failed to parse /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.30/package.nls.json: Value expected.
